# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy files
COPY pyproject.toml ./
COPY src ./src

# Install build dependencies
RUN pip install --upgrade pip
RUN pip install uv

# Install the project
RUN uv sync

# Expose default Sketchup port (if applicable)
EXPOSE 9876

# Command to run the MCP server
CMD ["cg-mcp"] 