# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy files
COPY pyproject.toml ./
COPY compliance_global_ai/ ./compliance_global_ai

# Install build dependencies
RUN pip install --upgrade pip
RUN pip install uv

# Install the project
RUN uv sync
RUN uv pip install -e . --no-cache-dir

# Expose default Sketchup port (if applicable)
EXPOSE 8000

# Command to run the MCP server
CMD ["cg-mcp"] 